### ISSUE TITLE
Generated YAML has space before comments

### ISSUE THREAD

**Issue by rugk** [ENT8R/blacklistr#10]
E.g. https://ent8r.github.io/blacklistr/?java=tactile_paving/AddTactilePavingCrosswalk.java:

```yml
only
 # Europe
NO,SE,
GB,IE,NL,BE,FR,ES,
DE,PL,CZ,SK,HU,AT,CH,
LV,LT,EE,RU,
 # America
US,CA,AR,
 # Asia
HK,SG,KR,JP,
 # Oceania
AU,NZ,
``` 

The comments are not necessary.

**Comment by ENT8R** [comment]
This was also fixed as a nice side-effect of b641d94 😄
