### ISSUE TITLE
YAML and StreetComplete

### ISSUE THREAD

**Issue by rugk** [ENT8R/blacklistr#11]
I just looked into that again, and was quite surprised to see blacklistr does some format conversion and does not support the exactly format, that StreetComplete uses.

Does not this defeat one whole use case?

Because as a StreetComplete developer/contributor/... I want to have a simple copy & paste workflow.

I.e. I want to:
1. Load the file in blacklistr
2. Do some changes (click on countries, or do it manually).
3. Copy the output and add it back into the source file in StreetComplete.

The third thing is not possible, because the syntax is different. And doing the conversion back by hand, totally defeats the purpose of blacklistr - then I can also just edit it by hand.

/cc @westnordost

**Comment by westnordost** [comment]
Current behaviour is ok by me

**Comment by ENT8R** [comment]
I think the only thing which has to be changed are the comments: They should not begin with an `#` but instead with a double slash (`//`).
Ah, and there have to be quotation marks around the single countries...

**Comment by rugk** [comment]
> is ok by me

Well… _okay_ just reflects that situation. Not very user friendly…
We can live with that sure, but why make it harder for ourself, when we already have such tools?

As for the comments, mhh, one could do that in some time (still annoying, but possible/reasonable), but adding quotation marks around each entry is cumbersome… If I have to do that, I'd rather manually write these entries.

**Comment by ENT8R** [comment]
With d59c221 the input is now more like Javascript/Java instead of YAML.
What does not work now anymore is comments beginning with `#` but this should be no problem (The comments begin now with a double-slash `//`)
Quotation marks are still not required but automatically set if you click on a country (for easier copy-pasting 😄).
