### ISSUE TITLE
Undefined in list of countries

### ISSUE THREAD

**Issue by rugk** [ENT8R/blacklistr#15]
https://ent8r.github.io/blacklistr/?java=housenumber/AddHousenumber.java

> Blacklisted in Netherlands, undefined, Denmark, undefined, Norway, undefined, Czech Republic

:laughing:

**Comment by ENT8R** [comment]
Mmhh Okay... But this should be pretty easy to fix...

**Comment by ENT8R** [comment]
Should be fixed now...
