### ISSUE TITLE
Image export

### ISSUE THREAD

**Issue by rugk** [ENT8R/blacklistr#2]
It would be awesome if I can export the image for the Quests wiki.

From https://github.com/westnordost/StreetComplete/pull/824#issuecomment-362734402:
> By the way, rugk, this would also be great for your Quests wiki page, to show where certain quests are enabled or disabled.

From https://github.com/westnordost/StreetComplete/pull/824#issuecomment-362792259:
> so you can export the image as a PNG, or, better, SVG (otherwise we'd have to screenshot this, but that may not be nice, e.g. one may want a transparent background and the same size, which us hard when screenshotting)

**Comment by ENT8R** [comment]
Does that feature work for you?

**Comment by rugk** [comment]
It works, great, but it is really only a screenshot.
What I'd need for the wiki is, especiaally, images of the same size and style, i.e. could not you just always return the full-sized image of the whole map/world without caring for the zoom level?

Of course, please crop the image in a way that you don't see America twice as you do currently when zooming out. (Generally, if possible, you can also prevent this even when viewing the website.)

**Comment by ENT8R** [comment]
The problem is that the plugin I use can only take screenshots of what is really visible on the map. So I will set the map to 30°N, 0°E and zoom 2 which is the default setting when you open the map and should cover the whole world

**Comment by rugk** [comment]
Hmm okay, possibly you could also just zoom out when one presses the button there. But if the default zoom works, that may also be enough.

However I found some other issues:
1. The filename has no file extension. Just add `.png`. 😄 (Especially on WIndows that is bad.)
2. As you can see the image below, which I just created and on the left and top there are empty parts and on the right the map begins again. Both things should not be there.

![blacklistr-screenshot](https://user-images.githubusercontent.com/11966684/35777684-7e09cd28-09b2-11e8-91dd-db091e6249f8.png)

**Comment by ENT8R** [comment]
In the future expert mode there will be a reset button which you can click to reset the map to avoid those issues 🔝

**Comment by rugk** [comment]
I did not change the view. I opened the site and clicked onj the screenshot button, so it is already reset. :)

**Comment by ENT8R** [comment]
Oh... I will investigate...

**Comment by ENT8R** [comment]
> The filename has no file extension.

Should be fixed now.

> As you can see the image below,

I can't reproduce it... Is it still present?

**Comment by rugk** [comment]
Sorry, cannot test it. Currently the page just shows me the worldwide map, no buttons, no input, nothing to click at…

**Comment by ENT8R** [comment]
Then try https://ent8r.github.io/blacklistr/expert/?file=../assets/test.yaml

**Comment by rugk** [comment]
Ah, in expert mode, yes:

![blacklistr-screenshot](https://user-images.githubusercontent.com/11966684/35780283-3bc44976-09d9-11e8-95f3-024e523d40f8.png)

Firefox 58

Just clicked the link and clicked on the export icon.

**Comment by ENT8R** [comment]
But why is there a duplicate map on the right??? I can't reproduce it... Neither with Chrome or Firefox...

**Comment by westnordost** [comment]
Because he has a big screen, duh

**Comment by rugk** [comment]
But you can reproduce the empty area in the top left?

**Comment by ENT8R** [comment]
Mmhh.. No...

**Comment by rugk** [comment]
Ah, I think I found the problem: You maybe have a different browser window size. I just reproduced it with a completely different browser. Tray to make it as large as possible.
