### ISSUE TITLE
loading streetcomplete quests?

### ISSUE THREAD

**Issue by mnalis** [ENT8R/blacklistr#22]
https://github.com/ENT8R/blacklistr/blob/master/README.md mentions:

> To load the data used by [StreetComplete](https://github.com/streetcomplete/StreetComplete/) use the endpoint /?streetcomplete={questDirectory/questName}
> Example: [/?streetcomplete=housenumber/AddHousenumber.kt](https://ent8r.github.io/blacklistr/?streetcomplete=housenumber/AddHousenumber.kt)

However, that (example at least) doesn't seem to work for me (https://ent8r.github.io/blacklistr/?streetcomplete=housenumber/AddHousenumber.kt does not show any countries)

**Comment by ENT8R** [comment]
The README uses an old example, meanwhile the housenumber quest has been moved from housenumber to the address directory, so the correct example which also works should be:

> To load the data used by [StreetComplete](https://github.com/streetcomplete/StreetComplete/) use the endpoint `/?streetcomplete={questDirectory/questName}`
>
> Example: [`/?streetcomplete=address/AddHousenumber.kt`](https://ent8r.github.io/blacklistr/?streetcomplete=address/AddHousenumber.kt)
