### ISSUE TITLE
Third state: Disabled by default

### ISSUE THREAD

**Issue by rugk** [ENT8R/blacklistr#4]
From https://github.com/westnordost/StreetComplete/pull/824#issuecomment-362792259: 
> make sure there are tree colors/states for: enabled, disabled by default and blacklisted (the last one cannot be enabled manually in the setting)

States are:
* enabled = always shown
* disabled by default = (indoor quests) user can enable these in the settings
* blacklisted = user cannot enable them, they are not available in the country

I.e. especially for illustrations in the wiki this is useful (see https://github.com/ENT8R/blacklistr/issues/2).

**Comment by ENT8R** [comment]
> disabled by default

But aren't quests disabled by default, disabled in all countries?

**Comment by rugk** [comment]
Oh, yeah, currently, yes. Although I can certainly imagine that @westnordost may have a use case for disabling some by default only in some countries.
E.g. when we are unsure whether a quest is actually useful somewhere, we may, instead of blacklisting it directly, just disable it by default as a "softer" way of preventing people from abusing it.

Anyway my idea is to replace the whole "Notes" part in the wiki and there sometimes "disabled by default" is shown, so mhh…

As for this issue just a minor thing: Could you add a way to select "disabled by default" countries on the map? E.g. Shift+Click or Ctrl+Click?

**Comment by ENT8R** [comment]
It will be Crtl+Click
