### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by westnordost** [ENT8R/blacklistr#6]
Hi @ENT8R , man, you are quick. It is impressive how quickly you can whip something up like this. So, here are the promised requirements. What @rugk writes is well-meant, but in my opinion, he is missing the big picture. Since you already built most of it, I am just telling what I'd want to have changed:

**We have two use cases:**
1. View for which states the quest is enabled and why, if specified. The idea here is to be able to directly link a blacklistr page from the wiki which already includes all the information directly from repository:
  - so, no screenshot functionality. Best remove it to keep it as simple as possible
  - Hide all these controls and input fields by default, just show the map. The focus should be on the enabled/disabled countries.
  - Do not show the polygons for not-selected countries at all, it is clearer that way. Depending on whether it is a black- or whitelist, the selected polygons can be colored slightly green/red (or white/black ;-) ). Regarding that "show borders" option, I'd remove the option and always show borders but only for the selected polygons and in a color that is similar to the fill color (i.e. without alpha or slightly darker)
  - **Bonus**: blacklistr should be able to parse and show comments that are written for a country and show them (in a bubble) when clicking on the country. For example, currently in the `AddHousenumber` quest, there is a comment for each blacklisted country
  - finally, (after it has been implemented in StreetComplete), blacklistr should accept a url parameter from which the countries are loaded, whether it is a black- or whitelist etc. This way, @rugk can simply specify a link to blacklistr with the correct parameter pointing to the `master` of the StreetComplete repos and will never have to update this.
2. edit it easily by clicking on the countries. This is optional, really. Perhaps for simplicity sake, you want to remove it, because my requirements would make this edit-mode more sophisticated. It is more than enough to be able to edit it by writing into the input-field.
  - Input field: There should be just *one* input field, where the list is specified in a specific format and the map should update accordingly.
  - Again, I would advise to not make the map itself editable by clicking, because it makes the UI interaction more complex (i.e. how to select India as a whole? How to set a comment for a country selection?) and it becomes necessary to not only write a parser for that format, but a writer, which additionally mess up the comments or predefined order.

**Format**
I thought it would be best to have an own simple format for specifying these white/blacklists to have it both human readable and not verbose. It is basically a comma separated list + line comments + specifying whether it is a white-or blacklist. Here is an example file:

```
all except 
NL, # https://forum.openstreetmap.org/viewtopic.php?id=60356
DK, # https://lists.openstreetmap.org/pipermail/talk-dk/2017-November/004898.html
NO, # https://forum.openstreetmap.org/viewtopic.php?id=60357
CZ, # https://lists.openstreetmap.org/pipermail/talk-cz/2017-November/017901.html
```
or
```
# See https://ent8r.github.io/blacklistr?path=/app/src/main/assets/quest_blacklists/AddCycleway.txt

# #749. sources:
# Google Street View (driving around in virtual car)
# https://en.wikivoyage.org/wiki/Cycling
only 
DE, AT,NO, FI, IS, DK, CZ, HU,CH,ES,
IE,LU, FI,
LI, # may not have cycleways after all, bla bla bla
PL, # by local knowlege of xyz (forum link)
# US source: http://peopleforbikes.org/get-local/
US-WA,US-OR, HI, US-CA,US-AZ,
US-TX
```

So:
- it always starts with either `all except` or `only` (could also be `none except`, or `none but`... opinions?), then a space, and then...
- a list of country codes, separated by `,`
- comments start with `#` and go till the end of the line
- otherwise, line feeds are ignored

**Comment by ENT8R** [comment]
Sounds all doable! Maybe it is the best to have a "normal" mode and an "expert" mode, as the most part of the code already exists...
Thank you for the input! I will try to implement all of your proposals!

**Comment by rugk** [comment]
> blacklistr should accept a url parameter from which the countries are loaded, whether it is a black- or whitelist etc. This way, @rugk can simply specify a link to blacklistr with the correct parameter pointing to the master of the StreetComplete repos and will never have to update this.

I think the URL parameter is already implemented (@ENT8R already linked to it), it is just not visible in the UI. (My proposal: Via the history JS API you can just change the URL in the address bar, so you do not need yet another button.)

However, I don't exactly understand how I should link from the wiki. So I can surely link to `https://ent8r.github.io/blacklistr/#blacklist&DE,CA,…`, but when the country list changes, I still need to update it.
So do you propose that blacklistr should also accept a file as URL parameter, download it and display it then? So should it accept `https://ent8r.github.io/blacklistr/#file=https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/…/whatever-blacklist.yml` (or, actually, the RAW GitHub link, but you get the principle)

As for the simpel map view/expert mode question, I would simply propose to have a **<** icon at the right, where you can toggle the "sidebar". Just so you can hide and show the sidebar. And maybe only when the sidebar is shown, you can click on the map to edit it. (As I really like taht click feature, it is useful to fastly edit the list.)

**Comment by westnordost** [comment]
@rugk Yes. Or, to make it short, leave out `https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/` from the url parameter and let blacklistr complement that base path (because it is always the same).

**Comment by rugk** [comment]
(depends on whether you want to make that toool a general thing for such blacklists, or only for StreetComplete)

**Comment by ENT8R** [comment]
> so, no screenshot functionality. Best remove it to keep it as simple as possible

Is now included only in the expert mode

> Hide all these controls and input fields by default, just show the map.

Done (only shown in expert mode)

> Do not show the polygons for not-selected countries at all, it is clearer that way.

Do you really think that this is a good idea? This way one can't see really where it is blacklisted if the `only` statement is used... It could be also enabled because it has nearly the same color...

> Bonus: blacklistr should be able to parse and show comments that are written for a country and show them (in a bubble) when clicking on the country.

Done and implemented in both modes

> finally, (after it has been implemented in StreetComplete), blacklistr should accept a url parameter from which the countries are loaded, whether it is a black- or whitelist etc.

Done! Try it out using
https://ent8r.github.io/blacklistr/?file=assets/test.yaml
or https://ent8r.github.io/blacklistr/expert/?file=../assets/test.yaml

> and it becomes necessary to not only write a parser for that format, but a writer, which additionally mess up the comments or predefined order.

Good point... I removed it now. Sorry @rugk ....

> I thought it would be best to have an own simple format for specifying these white/blacklists to have it both human readable and not verbose.

I used the format you proposed.

**Comment by westnordost** [comment]
Noice! Though, you did not do 
> Do not show the polygons for not-selected countries at all, it is clearer that way. Depending on whether it is a black- or whitelist, the selected polygons can be colored slightly green/red (or white/black ;-) ). Regarding that "show borders" option, I'd remove the option and always show borders but only for the selected polygons and in a color that is similar to the fill color (i.e. without alpha or slightly darker)

which in effect makes it look like no country in US is whitelisted.

**Comment by ENT8R** [comment]
Mmhh... yeah right. I will change this.

**Comment by ENT8R** [comment]
Is it better now?

**Comment by rugk** [comment]
It is heavily [confusing](https://github.com/ENT8R/blacklistr/issues/2#issuecomment-362923735) if you only see an empty map…
And separating expert mode into another html file is a bit strange.

So why not add a simple toggle at the right, which opens a sidebar when clicked. This would then just convert the view into the "expert mode". I've already described this in detail:

> As for the simple map view/expert mode question, I would simply propose to have a < icon at the right, where you can toggle the "sidebar". Just so you can hide and show the sidebar. And maybe only when the sidebar is shown, you can click on the map to edit it. (As I really like taht click feature, it is useful to fastly edit the list.)

Also, at least in the expert mode, you could allow one to click on the countries.

**Comment by ENT8R** [comment]
> Also, at least in the expert mode, you could allow one to click on the countries.

But this would override the feature to display comments on click... This is why I created a seperate file...

**Comment by westnordost** [comment]
I concur with all of @rugk 's points in his last post except the last.

**Comment by westnordost** [comment]
By now, the "expert" mode constitutes of one input that (weirdly) expands and a button.

How about removing expert mode and simply showing the loaded configuration file directly on the right side (input field covers the complete "panel"), a bit like in Tangram Play, and every keystroke in the input updates the map on the left, no button necessary.

Since the configuration file is quite well human readable, this could be the default view, so map + text. Then, you could also remove the comments from being displayed as bubbles on the map, because it is already visible on the right.

**Comment by ENT8R** [comment]
OK. Good idea. I will do this.

**Comment by ENT8R** [comment]
But what about the screenshot button?

**Comment by rugk** [comment]
> But this would override the feature to display comments on click... 

Huh, what? Did not see that, but a good idea.
So okay, why not?
* show comments on click in usual mode
* select/unselect countries in expert mode

Or, as I read this:
> could also remove the comments from being displayed as bubbles on the map

So we can have the map click to select/unselect back as it does not clash with the comments feature anymore?

**Comment by ENT8R** [comment]
> So we can have the map click to select/unselect back as it does not clash with the comments feature anymore?

I will probably do this tomorrow...

With the latest commit I added a new editor (the one Tangram Play uses too) and removed the expert mode...

**Comment by rugk** [comment]
Yeah, looks great so far!

As another addition: Maybe a "load file" dialog or so would be useful. As the map is still quite empty when you open the page without a parameters. And one does not know the syntax in such a state.
Or just show an example by default or so…

**Comment by westnordost** [comment]
Oh man, don't overdo the complexity please. It's not as if we have to edit the country blacklists every day. It should just serve as a handy overview, nothing more.

Actually, I am getting second thoughts regarding this special
```none except XY, AB, CD # this is my comment```
format, because it means that the information is stored away from the actual quest, plus, every single quest would need to have a reference to the Android AssetManager, it seems. I started implementing this today but reverted everything again because I need to think about whether the pros weigh out the cons here.

**Comment by westnordost** [comment]
**Pro**:
- Overview can be linked to raw file from repos (in wiki), without having to update it each time it is updated in the repos
- Slightly better readable in this text format than in Java code

**Con**:
- It is not immediately visible by looking at the code of the quest that it is indeed disabled for certain countries (<- found this out during implementation )
- The configuration is removed from the quest, even though it belongs to it, scattering the logic over the project
- To open the raw file, a reference to the asset manager is necessary but not available. It would need to be passed down to every quest in the QuestsModule to be used (only) to read the file in the currently 5 cases where this is done. The question is: Does it make sense for quests to use the asset manager to access some other resources perhaps? I'd say: no

(Though, to be mean, the first "pro" reason should only be a courtesy, a side product, and not determine how to design the app architecturally)

**Comment by rugk** [comment]
Yeah, maybe better keep it in the code. So can't the website also just parse the Java code somehow (in an easy way!). E.g. you could include special markers via coments in the source code to make it easy to parse. Or just a private (or whatever) function with a static name, which only returns that config as a string. That could also be easy to parse for the website.

**Comment by ENT8R** [comment]
> So we can have the map click to select/unselect back as it does not clash with the comments feature anymore?

This feature is back now. It was not that complicated to create a writer for that...

> Or just show an example by default or so…

I did this now... The other proposals where indeed too complex...

---
Regarding the amount of pros and cons, I would say: leave it in the code! Maybe there is a way to parse the java code with this tool...

**Comment by westnordost** [comment]
Well, you could scrape the java code for that: Search for the first "{" after the "getEnabledForCountries" and put only the string that is between that and the closing brace in the editor.
Then, interpret "return Countries.allExcept(new String[]...." the same as before simply "all except" etc...

Am 5. Februar 2018 14:32:32 MEZ schrieb ENT8R <notifications@github.com>:
>> So we can have the map click to select/unselect back as it does not
>clash with the comments feature anymore?
>
>This feature is back now. It was not that complicated to create a
>writer for that...
>
>> Or just show an example by default or so…
>
>I did this now... The other proposals where indeed too complex...
>
>---
>Regarding the amount of pros and cons, I would say: leave it in the
>code! Maybe there is a way to parse the java code with this tool...
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ENT8R/blacklistr/issues/6#issuecomment-363085391

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ENT8R** [comment]
Thank you for the hint!
It is now implemented and should work... But if there are issues please report them immediately here so I can fix them...

Here are some examples:
**Maxspeed quest**
https://ent8r.github.io/blacklistr/?java=max_speed/AddMaxSpeed.java

**Housenumber quest**
https://ent8r.github.io/blacklistr/?java=housenumber/AddHousenumber.java

**New tactile paving limitation (crosswalks)**
https://ent8r.github.io/blacklistr/?java=https://raw.githubusercontent.com/matkoniecz/Zazolc/tactile/app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/AddTactilePavingCrosswalk.java

**New tactile paving limitation (bus stops)**
https://ent8r.github.io/blacklistr/?java=https://raw.githubusercontent.com/matkoniecz/Zazolc/tactile/app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/AddTactilePavingBusStop.java

**Comment by rugk** [comment]
Awesome!

**Comment by westnordost** [comment]
Very cool!
The links to these pages could be added as comments to the methods in the quests in StreetComplete, for overview.
