### ISSUE TITLE
java=tactile_paving/AddTactilePavingCrosswalk.java won't work

### ISSUE THREAD

**Issue by westnordost** [ENT8R/blacklistr#7]
https://ent8r.github.io/blacklistr/?java=tactile_paving/AddTactilePavingCrosswalk.java doesn't work. 

Perhaps change the parsing to look for `Countries\.noneExcept\s*(\s*new\s+String\s*\[\]` instead of `getEnabledForCountries`?

**Comment by ENT8R** [comment]
Oh yeah... I will do this!
