### ISSUE TITLE
Add links to wiki

### ISSUE THREAD

**Issue by rugk** [ENT8R/blacklistr#9]
I'll do that, just want to have an issue for that, here. You can assign me, if that is possible.

**Comment by ENT8R** [comment]
Alright! Thank you for doing this!

**Comment by rugk** [comment]
Okay, so I [did add the ones I found](https://wiki.openstreetmap.org/w/index.php?title=StreetComplete%2FQuests&type=revision&diff=1598330&oldid=1598195). I hope I got all of them. :smile:

**Comment by ENT8R** [comment]
Great! Thank you!
